# Generated by Django 4.0.6 on 2022-07-28 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assunto_formacao', to='recursos.area_especifica')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacao_formador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacoes.formacao')),
                ('formando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formando', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao_Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('isapoio', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_recurso', to='formacoes.formacao')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_recurso', to='recursos.recurso')),
            ],
        ),
    ]
