# Generated by Django 4.0.6 on 2022-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='imagem',
            field=models.ImageField(null=True, upload_to='capas/'),
        ),
    ]
