# Generated by Django 4.0.6 on 2022-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_licenca_recurso_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='isactivo',
            field=models.IntegerField(default=0),
        ),
    ]
