# Generated by Django 4.0.6 on 2022-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_recurso_isactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca',
            name='imagem',
            field=models.ImageField(upload_to='recursos/static/licencas'),
        ),
    ]
