# Generated by Django 4.0.6 on 2022-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_alter_licenca_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='ficheiro',
            field=models.FileField(null=True, upload_to='recurso/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fonte',
            name='co_autor',
            field=models.TextField(null=True),
        ),
    ]
