# Generated by Django 4.0.6 on 2022-07-28 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assunto_podcast', to='recursos.area_especifica')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador_podcast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito_podcast', to=settings.AUTH_USER_MODEL)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrito_podcast', to='podcasts.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('numero', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio_podcast', to='podcasts.podcast')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio_podcast', to='recursos.recurso')),
            ],
        ),
    ]
